"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Activity, ArrowDownToLine, ArrowRight, Check, ChevronLeft, ChevronRight, CircleHelp, Clock3, FileJson, FlaskConical, GitBranch, Import, Pause, Play, Radio, RotateCcw, Settings2, ShieldCheck, Waves, WifiOff, X, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Slider } from "@/components/ui/slider";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogHeader, DialogTrigger } from "@/components/ui/dialog";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Input } from "@/components/ui/input";
import { analyze, BATTERY, Budgets, compare, defaults, download, Finding, htmlReport, Scenario, scenarios, simulate, SPEED, stateAt, Trace, traceSchema } from "@/lib/trace";

const base = process.env.NEXT_PUBLIC_BASE_PATH || "";
const repo = "https://github.com/abrar0205/ignition-trace";
const colors = { signal: "#2757d8", frame: "#d66b35", span: "#008b80", audio: "#8765c5", playback: "#8765c5", lifecycle: "#7d899b" };
const fmt = (v: number | null | undefined, digits = 0) => v == null ? "—" : v.toLocaleString("en-US", { maximumFractionDigits: digits });
const stamp = (t: number) => `${Math.floor(t / 60000).toString().padStart(2, "0")}:${(t / 1000 % 60).toFixed(2).padStart(5, "0")}`;
const labels: Record<keyof Budgets, string> = { frame_ms: "Frame duration", network_ms: "Network request", startup_ms: "App startup", audio_resume_ms: "Audio recovery", signal_gap_ms: "Speed signal freshness" };

function RouteView({ progress }: { progress: number }) {
  // Abstract route artwork, not geographic location or measured distance.
  const x = 28 + 304 * progress;
  return <svg viewBox="0 0 360 110" className="route-view" role="img" aria-label="Abstract drive progress, not a geographic map">
    <defs><pattern id="route-grid" width="18" height="18" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".65" fill="#c1c9d7" /></pattern></defs>
    <rect width="360" height="110" fill="url(#route-grid)" />
    <path d="M28 80H80Q110 80 110 50V36Q110 20 134 20H205Q230 20 230 45V62Q230 80 255 80H332" fill="none" stroke="#d5ddec" strokeWidth="16" strokeLinecap="round" />
    <path d="M28 80H80Q110 80 110 50V36Q110 20 134 20H205Q230 20 230 45V62Q230 80 255 80H332" fill="none" stroke="#fff" strokeDasharray="4 5" strokeWidth="1.5" />
    <circle cx="28" cy="80" r="5" fill="#fff" stroke="#2454d6" strokeWidth="2" /><circle cx="332" cy="80" r="5" fill="#fff" stroke="#2454d6" strokeWidth="2" />
    <path d={`M${x} 98v-8`} stroke="#ee7140" strokeWidth="3" /><text x="28" y="105" fontSize="9" fill="#5d6c83">START</text><text x="305" y="105" fontSize="9" fill="#5d6c83">FINISH</text>
  </svg>;
}

function Timeline({ trace, cursor, setCursor, finding, span }: { trace: Trace; cursor: number; setCursor: (v: number) => void; finding: Finding | null; span: number }) {
  const half = Math.min(span, trace.duration_ms) / 2;
  const center = Math.max(half, Math.min(trace.duration_ms - half, cursor));
  const start = center - half, end = center + half;
  const x = (t: number) => 110 + (t - start) / Math.max(1, end - start) * 750;
  const lanes = ["signal", "audio", "frame", "span"] as const;
  const inView = trace.events.filter(e => e.t_ms >= start && e.t_ms <= end);
  return <div className="timeline-scroll"><svg viewBox="0 0 888 260" role="img" aria-label="Four synchronized event lanes. Use the replay slider to seek." onClick={event => { const b = event.currentTarget.getBoundingClientRect(); const t = start + (((event.clientX - b.left) / b.width * 888 - 110) / 750) * (end - start); setCursor(Math.max(0, Math.min(trace.duration_ms, t))); }}>
    {Array.from({ length: 7 }, (_, i) => <g key={i}><path d={`M${110 + i * 125} 25V232`} stroke="#e7eaf0" strokeDasharray="3 5" /><text x={110 + i * 125} y="16" textAnchor="middle" className="svg-tick">{fmt((start + (end - start) * i / 6) / 1000, 1)}s</text></g>)}
    {lanes.map((lane, i) => { const y = 58 + i * 53; const events = inView.filter(e => lane === "audio" ? e.kind === "audio" || e.kind === "playback" : lane === "signal" ? e.kind === "signal" && e.name === SPEED : e.kind === lane); const stride = Math.max(1, Math.ceil(events.length / 800));
      return <g key={lane}><text x="8" y={y + 4} className="svg-label">{["VEHICLE", "AUDIO", "FRAMES", "NETWORK"][i]}</text><line x1="110" x2="860" y1={y + 17} y2={y + 17} stroke="#e4e8ef" />{events.filter((_, j) => j % stride === 0).map(e => lane === "signal" ? <line key={e.seq} x1={x(e.t_ms)} x2={x(e.t_ms)} y1={y + 15} y2={y + 15 - Math.max(2, Math.min(34, Number(e.value) / 110 * 34))} stroke={colors[lane]} strokeWidth="2.5" opacity=".8" /> : <rect key={e.seq} x={x(e.t_ms)} y={y - (lane === "frame" ? Math.min(30, (e.duration_ms || 0) / 5) : 8)} width={Math.max(lane === "audio" ? 6 : 3, Math.min(860 - x(e.t_ms), (e.duration_ms || 0) / (end - start) * 750))} height={lane === "frame" ? Math.max(3, Math.min(30, (e.duration_ms || 0) / 5)) + 15 : 21} rx="2" fill={colors[lane]} opacity=".85" />)}</g>;
    })}
    {finding && finding.end_ms >= start && finding.start_ms <= end && <rect x={Math.max(110, x(finding.start_ms))} y="27" width={Math.max(3, Math.min(860, x(finding.end_ms)) - Math.max(110, x(finding.start_ms)))} height="207" fill="#f07c39" opacity=".12" />}
    <line x1={x(cursor)} x2={x(cursor)} y1="25" y2="235" stroke="#152a4b" strokeWidth="1.5" /><circle cx={x(cursor)} cy="25" r="4" fill="#152a4b" /><text x="110" y="255" className="svg-tick">Click to seek · dense recordings are visually sampled</text>
  </svg></div>;
}

export default function Home() {
  const [trace, setTrace] = useState<Trace>(() => simulate("mixed"));
  const [scenario, setScenario] = useState<Scenario>("mixed"), [seed, setSeed] = useState(42);
  const [budgets, setBudgets] = useState<Budgets>(defaults), [draft, setDraft] = useState<Budgets>(defaults), [settingsOpen, setSettingsOpen] = useState(false);
  const [cursor, setCursor] = useState(20400), [playing, setPlaying] = useState(false), [rate, setRate] = useState("1"), [zoom, setZoom] = useState("full");
  const [tab, setTab] = useState("replay"), [selected, setSelected] = useState<string | null>(null), [search, setSearch] = useState(""), [kind, setKind] = useState("all"), [page, setPage] = useState(0);
  const [notice, setNotice] = useState("Synthetic drive loaded. Select a finding to investigate."), [error, setError] = useState(false);
  const [baseline, setBaseline] = useState<Trace>(() => simulate("clean")), [local, setLocal] = useState(false), [archive, setArchive] = useState<{ id: string; title: string; source: string; created: string }[]>([]), [busy, setBusy] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null), baselineRef = useRef<HTMLInputElement>(null);
  const report = useMemo(() => analyze(trace, budgets), [trace, budgets]);
  const baselineReport = useMemo(() => analyze(baseline, budgets), [baseline, budgets]);
  const deltas = useMemo(() => compare(baselineReport, report), [baselineReport, report]);
  const state = useMemo(() => stateAt(trace, cursor), [trace, cursor]);
  const finding = report.findings.find(f => f.id === selected) || null;
  const speed = state.signals.get(SPEED), battery = state.signals.get(BATTERY);
  const visibleEvents = useMemo(() => trace.events.filter(e => (kind === "all" || e.kind === kind) && (!finding || finding.evidence.includes(e.seq)) && `${e.name} ${e.source} ${e.value}`.toLowerCase().includes(search.toLowerCase())), [trace, kind, search, finding]);
  const tell = (message: string, bad = false) => { setNotice(message); setError(bad); };
  const accept = useCallback((t: Trace) => { setTrace(t); setCursor(0); setPlaying(false); setSelected(null); setPage(0); setZoom("full"); setSearch(""); setKind("all"); }, []);
  const run = useCallback((id: Scenario, value: number) => { const t = simulate(id, value); accept(t); setScenario(id); setSeed(value); setNotice("New synthetic trace generated locally. No network connection needed."); setError(false); }, [accept]);
  useEffect(() => { if (!playing) return; let last = performance.now(); const timer = setInterval(() => { const now = performance.now(), elapsed = now - last; last = now; setCursor(c => Math.min(trace.duration_ms, c + elapsed * Number(rate))); }, 50); return () => clearInterval(timer); }, [playing, rate, trace.duration_ms]);
  useEffect(() => { if (cursor >= trace.duration_ms) setPlaying(false); }, [cursor, trace.duration_ms]);
  useEffect(() => { let alive = true; fetch(`${base}/api/v1/health`, { signal: AbortSignal.timeout(2500) }).then(r => r.ok ? r.json() : null).then(v => { if (alive && (v as { mode?: string } | null)?.mode === "local") setLocal(true); }).catch(() => {}); return () => { alive = false; }; }, []);
  useEffect(() => { setPage(0); }, [kind, search, selected]);
  useEffect(() => {
    const context = (document as Document & { modelContext?: { registerTool: (tool: object, options: { signal: AbortSignal }) => unknown } }).modelContext;
    if (!context?.registerTool) return;
    const controller = new AbortController();
    try { void Promise.resolve(context.registerTool({ name: "run_ignition_scenario", description: "Generate and open a local synthetic infotainment trace.", inputSchema: { type: "object", properties: { scenario: { type: "string", enum: scenarios.map(s => s.id) }, seed: { type: "integer", minimum: 0, maximum: 4294967295 } }, required: ["scenario", "seed"], additionalProperties: false }, annotations: { readOnlyHint: false }, execute: (input: { scenario: Scenario; seed: number }) => { const t = simulate(input.scenario, input.seed); run(input.scenario, input.seed); return { title: t.title, events: t.events.length }; } }, { signal: controller.signal })).catch(() => {}); } catch {}
    return () => controller.abort();
  }, [run]);
  async function importTrace(file: File | undefined, asBaseline = false) {
    if (!file) return;
    try { if (file.size > 8 * 1024 * 1024) throw new Error("Trace exceeds the 8 MiB import limit."); const t = traceSchema.parse(JSON.parse(await file.text())); if (asBaseline) setBaseline(t); else accept(t); tell(`${asBaseline ? "Baseline" : "Trace"} opened locally: ${t.title}`); }
    catch { tell("Cannot open this file. Use a valid IgnitionTrace 1.0 trace, ordered events, and a maximum size of 8 MiB.", true); }
  }
  const focus = (f: Finding) => { setSelected(f.id); setCursor(f.start_ms); setPlaying(false); };
  async function refreshArchive() {
    const r = await fetch(`${base}/api/v1/traces`); if (!r.ok) throw new Error("Archive unavailable"); const data = await r.json(); if (!Array.isArray(data)) throw new Error("Invalid archive response"); setArchive(data.slice(0, 100));
  }
  async function saveArchive() { setBusy(true); try { const r = await fetch(`${base}/api/v1/traces`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(trace) }); if (!r.ok) throw new Error("Archive could not save this trace."); await refreshArchive(); tell("Trace saved to your local SQLite archive."); } catch { tell("Local archive unavailable. Check that the local API is running.", true); } finally { setBusy(false); } }

  return <div className="app-shell">
    <header className="masthead"><a className="brand" href={base + "/"} aria-label="IgnitionTrace home"><span className="brand-mark"><Zap size={24} fill="currentColor" /></span><span>Ignition<span className="brand-light">Trace</span><small>VEHICLE SOFTWARE LAB</small></span></a><div className="header-center"><span className="status-dot" /> {local ? "LOCAL ENGINE CONNECTED" : "BROWSER WORKBENCH"}</div><div className="header-actions"><Dialog><DialogTrigger asChild><Button variant="ghost" size="icon" aria-label="How the workbench works"><CircleHelp size={20} /></Button></DialogTrigger><DialogContent className="help-modal"><DialogHeader><DialogTitle>Built for the moments between systems.</DialogTitle><DialogDescription>IgnitionTrace is an engineering workbench for infotainment event traces.</DialogDescription></DialogHeader><p>Generate a drive, follow a finding to its evidence, and replay captured state. The demo is synthetic; imported Android traces contain actual recorded events.</p><p>Replay reconstructs event state. It does not reproduce the Android scheduler, control a real vehicle, or play recorded audio. Findings identify threshold violations, not root causes.</p><p>Import and analysis stay in this browser. The optional local API adds a SQLite archive. Session timestamps must share a monotonic clock; cross-device alignment is not inferred.</p><a href={repo + "/blob/main/docs/quickstart.md"} target="_blank" rel="noreferrer">Read the complete setup guide <ArrowRight size={15} /></a></DialogContent></Dialog><a href={repo} target="_blank" rel="noreferrer" className="source-link"><GitBranch size={17} /> Source code <ArrowRight size={15} /></a></div></header>
    <main className="workspace"><div className="workspace-heading"><div><p className="eyebrow">TRACE WORKBENCH <span>/</span> EXPERIMENT 01</p><h1>Understand the drive.</h1></div><div className="heading-actions"><Button variant="outline" onClick={() => inputRef.current?.click()}><Import size={16} /> Open trace</Button><Button onClick={() => download("ignition-trace.json", trace)}><ArrowDownToLine size={16} /> Export trace</Button></div></div>
    <input ref={inputRef} type="file" accept=".json,application/json" className="sr-only" aria-label="Import trace file" onChange={e => { void importTrace(e.target.files?.[0]); e.target.value = ""; }} /><input ref={baselineRef} type="file" accept=".json,application/json" className="sr-only" aria-label="Import baseline trace" onChange={e => { void importTrace(e.target.files?.[0], true); e.target.value = ""; }} />
    <div className="main-grid"><aside className="scenario-panel"><div className="panel-label"><FlaskConical size={16} /> FAULT LAB <span>01—06</span></div><h2>Choose a drive.</h2><p className="muted">Repeatable scenarios.<br />Real analysis, in your browser.</p><div className="scenario-list">{scenarios.map((s, i) => <button key={s.id} className={`scenario-option ${trace.source === "synthetic" && trace.scenario === s.id ? "active" : ""}`} onClick={() => run(s.id, seed)}><span className="scenario-index">0{i + 1}</span><span><strong>{s.name}</strong><small>{s.id === "clean" ? "REFERENCE DRIVE" : `${s.count} FAULT ${s.count === "01" ? "TYPE" : "TYPES"}`}</small></span><ArrowRight size={16} /></button>)}</div><div className="seed-row"><label htmlFor="seed">Scenario seed</label><Input id="seed" type="number" min="0" max="4294967295" step="1" value={seed} onChange={e => setSeed(Math.max(0, Math.min(4294967295, Math.floor(Number(e.target.value) || 0))))} /></div><Button className="rerun" variant="outline" onClick={() => run(scenario, seed)}><RotateCcw size={15} /> Generate new run</Button><div className="privacy-note"><ShieldCheck size={20} /><p><strong>Your traces stay yours.</strong><br />Browser imports stay on this device. No account or API key.</p></div><a className="android-link" href={repo + "/tree/main/android"} target="_blank" rel="noreferrer"><Radio size={19} /><span>Capture from Android<small>Recorder app + setup guide</small></span><ArrowRight size={16} /></a></aside>
    <div className="work-area"><div className="session-strip"><div><span className="session-icon"><Activity size={18} /></span><span><strong>{trace.title}</strong><small>{trace.source.toUpperCase()} · {trace.events.length} EVENTS · {(trace.duration_ms / 1000).toFixed(1)} SECONDS</small></span></div><span className={`run-tag ${report.finding_count ? "warn" : "pass"}`}>{report.finding_count ? `${report.finding_count} findings` : "Within budgets"}</span></div>
    <Tabs value={tab} onValueChange={setTab}><div className="tabs-bar"><TabsList className="work-tabs"><TabsTrigger value="replay">Replay studio</TabsTrigger><TabsTrigger value="evidence">Event explorer</TabsTrigger><TabsTrigger value="compare">Compare runs</TabsTrigger><TabsTrigger value="archive">Local archive</TabsTrigger></TabsList><Dialog open={settingsOpen} onOpenChange={v => { setSettingsOpen(v); if (v) setDraft(budgets); }}><DialogTrigger asChild><Button variant="ghost" size="icon" aria-label="Edit analysis budgets"><Settings2 size={18} /></Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Define your performance budgets</DialogTitle><DialogDescription>Project thresholds in milliseconds. These are engineering budgets, not automotive safety limits. Applied equally to both comparison runs.</DialogDescription></DialogHeader>{Object.entries(labels).map(([key, label]) => <label className="budget-row" key={key}>{label}<Input type="number" min="1" max={key === "frame_ms" ? "1000" : "60000"} value={draft[key as keyof Budgets]} onChange={e => setDraft(d => ({ ...d, [key]: Number(e.target.value) }))} /></label>)}<Button onClick={() => { try { analyze(trace, draft); setBudgets({ ...draft }); setSettingsOpen(false); setSelected(null); tell("Analysis and comparison updated with your budgets."); } catch { tell("Budgets must be positive; frames ≤ 1000 ms, other budgets ≤ 60000 ms.", true); } }}>Apply budgets</Button><Button variant="outline" onClick={() => setDraft(defaults)}>Restore defaults</Button></DialogContent></Dialog></div>
    <TabsContent value="replay"><div className="replay-top"><div className="vehicle-card"><div className="card-heading"><span className="eyebrow">CAPTURED VEHICLE STATE</span><span className="mini-pill">{speed && speed.age_ms > budgets.signal_gap_ms ? "STALE" : speed ? "AVAILABLE" : "NO SIGNAL"}</span></div><div className="vehicle-readout"><div><strong>{fmt(typeof speed?.value === "number" ? speed.value : null)}</strong><span>km/h</span></div><div className="battery"><span className="battery-icon"><span style={{ width: `${typeof battery?.value === "number" ? Math.max(0, Math.min(100, battery.value)) : 0}%` }} /></span><strong>{fmt(typeof battery?.value === "number" ? battery.value : null, 1)}%</strong><small>BATTERY</small></div></div><RouteView progress={cursor / trace.duration_ms} /><div className="vehicle-foot"><span>Abstract drive progress</span><span>{speed ? `${fmt(speed.age_ms)} ms since update` : "No speed measurement"}</span></div></div><div className="media-card"><div className="card-heading"><span className="eyebrow">HEAD UNIT / MEDIA STATE</span><Waves size={18} /></div><div className="media-body"><div className={`record ${state.playback === "playing" && playing ? "spinning" : ""}`}><span><Zap size={20} /></span></div><div><p>{state.playback === "playing" ? "Playback active" : state.playback === "paused" ? "Playback paused" : "Awaiting playback"}</p><h3>{trace.source === "synthetic" ? "Alpine Frequencies" : "Captured audio session"}</h3><small>{trace.source === "synthetic" ? "Synthetic media events · no audio output" : "State reported by the recorder"}</small></div></div><div className="media-track"><span style={{ width: `${cursor / trace.duration_ms * 100}%` }} /></div><div className="media-foot"><span>{stamp(cursor)}</span><span><span className="status-dot" /> {String(state.playback).toUpperCase()}</span><span>{stamp(trace.duration_ms)}</span></div></div></div>
    <div className="metrics-row">{[["FRAME P95", report.metrics.frame_p95_ms, "Measured frame durations"], ["NETWORK P95", report.metrics.network_p95_ms, "Completed request spans"], ["AUDIO RECOVERY", report.metrics.audio_resume_max_ms, "Longest observed recovery"], ["APP STARTUP", report.metrics.startup_max_ms, "Longest startup span"]].map(([label, value, help]) => <div className="metric" key={String(label)}><span>{label}</span><strong>{fmt(value as number | null, 1)}<small> ms</small></strong><p>{help}</p></div>)}</div>
    <div className="timeline-card"><div className="card-heading"><div><h2>One clock. Every event.</h2><p className="muted">Inspect the sequence across the vehicle and head unit.</p></div><Select value={zoom} onValueChange={setZoom}><SelectTrigger className="zoom-select" aria-label="Timeline window"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="full">Full recording</SelectItem><SelectItem value="10000">10 second window</SelectItem><SelectItem value="3000">3 second window</SelectItem></SelectContent></Select></div><Timeline trace={trace} cursor={cursor} setCursor={setCursor} finding={finding} span={zoom === "full" ? trace.duration_ms : Number(zoom)} /><div className="transport"><Button size="icon" aria-label={playing ? "Pause replay" : "Play replay"} onClick={() => { if (cursor >= trace.duration_ms) setCursor(0); setPlaying(!playing); }}>{playing ? <Pause size={17} /> : <Play size={17} />}</Button><Button variant="ghost" size="icon" aria-label="Restart replay" onClick={() => { setCursor(0); setPlaying(false); }}><RotateCcw size={17} /></Button><span className="timecode">{stamp(cursor)}</span><Slider aria-label="Replay position" min={0} max={trace.duration_ms} step={10} value={[cursor]} onValueChange={v => setCursor(v[0])} /><span className="duration-label">{stamp(trace.duration_ms)}</span><Select value={rate} onValueChange={setRate}><SelectTrigger className="rate-select" aria-label="Playback speed"><SelectValue /></SelectTrigger><SelectContent>{["0.5", "1", "2", "4"].map(r => <SelectItem key={r} value={r}>{r}×</SelectItem>)}</SelectContent></Select></div></div>
    </TabsContent>
    <TabsContent value="evidence"><div className="explorer"><div className="card-heading"><div><h2>Follow the evidence.</h2><p className="muted">Original timestamps and event identities, preserved.</p></div><span className="mini-pill">{visibleEvents.length} EVENTS</span></div><div className="event-filters"><Input aria-label="Search events" placeholder="Search signal, source, or value…" value={search} onChange={e => setSearch(e.target.value)} /><Select value={kind} onValueChange={setKind}><SelectTrigger aria-label="Event kind"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All event types</SelectItem>{Object.keys(colors).map(k => <SelectItem key={k} value={k}>{k}</SelectItem>)}</SelectContent></Select></div>{finding && <div className="evidence-banner">Evidence for: {finding.title}<Button size="sm" variant="ghost" onClick={() => setSelected(null)}>Clear filter <X size={14} /></Button></div>}<Table><TableHeader><TableRow><TableHead>Time</TableHead><TableHead>Type</TableHead><TableHead>Event</TableHead><TableHead>Value / duration</TableHead><TableHead>Source</TableHead><TableHead>ID</TableHead></TableRow></TableHeader><TableBody>{visibleEvents.slice(page * 30, page * 30 + 30).map(e => <TableRow key={e.seq} onClick={() => setCursor(e.t_ms)}><TableCell className="mono">{stamp(e.t_ms)}</TableCell><TableCell><span className="event-kind" style={{ color: colors[e.kind] }}>{e.kind}</span></TableCell><TableCell className="event-name">{e.name}<small>{e.correlation_id}</small></TableCell><TableCell>{e.duration_ms != null ? `${fmt(e.duration_ms, 2)} ms` : String(e.value ?? "—")}</TableCell><TableCell>{e.source}</TableCell><TableCell className="mono">#{e.seq}</TableCell></TableRow>)}</TableBody></Table>{!visibleEvents.length && <p className="empty-state">No events match this selection. Clear the finding filter or change your search.</p>}<div className="pagination"><span>Page {page + 1} of {Math.max(1, Math.ceil(visibleEvents.length / 30))}</span><Button variant="outline" size="icon" aria-label="Previous page" disabled={page === 0} onClick={() => setPage(p => p - 1)}><ChevronLeft size={16} /></Button><Button variant="outline" size="icon" aria-label="Next page" disabled={(page + 1) * 30 >= visibleEvents.length} onClick={() => setPage(p => p + 1)}><ChevronRight size={16} /></Button></div></div></TabsContent>
    <TabsContent value="compare"><div className="comparison"><div className="card-heading"><div><h2>Did this run get better?</h2><p className="muted">Both traces are analyzed with the same budgets.</p></div><Button variant="outline" onClick={() => baselineRef.current?.click()}><Import size={15} /> Open baseline</Button></div><div className="compare-titles"><div><span className="eyebrow">BASELINE</span><h3>{baseline.title}</h3><p>{baseline.source} · {baseline.events.length} events</p></div><ArrowRight size={24} /><div><span className="eyebrow">CANDIDATE</span><h3>{trace.title}</h3><p>{trace.source} · {trace.events.length} events</p></div></div><Table><TableHeader><TableRow><TableHead>Measurement</TableHead><TableHead>Baseline</TableHead><TableHead>Candidate</TableHead><TableHead>Change</TableHead></TableRow></TableHeader><TableBody>{Object.entries(report.metrics).map(([key, value]) => <TableRow key={key}><TableCell>{key.replaceAll("_", " ").replace(" ms", "")}</TableCell><TableCell>{fmt(baselineReport.metrics[key as keyof typeof report.metrics], 1)} ms</TableCell><TableCell>{fmt(value, 1)} ms</TableCell><TableCell className={(deltas[key] || 0) > 0 ? "regression" : "improvement"}>{deltas[key] == null ? "Not comparable" : `${deltas[key]! > 0 ? "+" : ""}${fmt(deltas[key], 1)} ms`}</TableCell></TableRow>)}</TableBody></Table><div className="compare-footer"><p>{report.finding_count} candidate findings · {baselineReport.finding_count} baseline findings. Differences show association, not causal attribution.</p><Button variant="outline" onClick={() => { setBaseline(trace); tell("Current trace pinned as baseline."); }}>Pin current as baseline</Button></div></div></TabsContent>
    <TabsContent value="archive"><div className="archive-panel"><span className="large-icon"><FileJson size={30} /></span><h2>{local ? "Your local trace archive." : "Keep a history on your own machine."}</h2><p className="muted">The browser workbench opens and exports traces without a server. Run the included Python API to persist recordings in SQLite and reopen them later.</p>{local ? <div className="archive-actions"><Button disabled={busy} onClick={saveArchive}>{busy ? "Saving…" : "Save current trace"}</Button><Button variant="outline" onClick={() => refreshArchive().catch(() => tell("Could not load the local archive.", true))}>Refresh archive</Button></div> : <a href={repo + "/blob/main/docs/quickstart.md"} target="_blank" rel="noreferrer" className="source-link">Local setup guide <ArrowRight size={16} /></a>}{archive.map(item => <button className="archive-item" key={item.id} onClick={async () => { try { const r = await fetch(`${base}/api/v1/traces/${encodeURIComponent(item.id)}`); if (!r.ok) throw new Error(); accept(traceSchema.parse(await r.json())); setTab("replay"); tell("Archived trace opened."); } catch { tell("Could not open archived trace.", true); } }}><FileJson size={18} /><span><strong>{item.title}</strong><small>{item.created} · {item.source}</small></span><ArrowRight size={18} /></button>)}</div></TabsContent>
    </Tabs><div className={`notice ${error ? "notice-error" : ""}`} role="status">{error ? <WifiOff size={16} /> : <Check size={16} />} {notice}</div></div>
    <aside className="findings-panel"><div className="panel-label"><Zap size={16} /> INVESTIGATION <span>{String(report.finding_count).padStart(2, "0")}</span></div><h2>Signals worth<br />a closer look.</h2><p className="muted">Select a finding to locate its exact moment in the recording.</p><div className="findings-list">{report.findings.map(f => <button className={`finding ${selected === f.id ? "selected" : ""}`} key={f.id} onClick={() => focus(f)}><span className="finding-time"><span />{stamp(f.start_ms)}</span><strong>{f.title}</strong><span className="finding-measure">{fmt(f.observed_ms)} ms <span>/ {fmt(f.budget_ms)} ms budget</span></span><small>{f.source} <ArrowRight size={14} /></small></button>)}{report.finding_count === 0 && <div className="clean-state"><ShieldCheck size={36} /><strong>No budget violations</strong><p>The configured checks passed for the observed events.</p></div>}</div>{finding && <div className="selected-evidence"><span className="eyebrow">SELECTED EVIDENCE</span><p>Events {finding.evidence.map(id => `#${id}`).join(" → ")}</p><Button size="sm" onClick={() => setTab("evidence")}>Inspect events <ArrowRight size={14} /></Button><Button variant="ghost" size="sm" onClick={() => setSelected(null)}>Clear</Button></div>}{report.omitted_findings > 0 && <p>{report.omitted_findings} additional findings omitted from detail.</p>}<div className="report-download"><h3>Take the evidence with you.</h3><p>Portable traces. Shareable findings.</p><Button variant="outline" onClick={() => download("ignition-report.html", htmlReport(trace, report), "text/html")}><ArrowDownToLine size={15} /> Download report</Button></div></aside></div>
    <footer><span><span className="footer-spark">✳</span> IgnitionTrace <span className="footer-version">v0.1</span></span><span>Open source. Inspectable by design.</span><a href={repo + "/blob/main/docs/methods.md"} target="_blank" rel="noreferrer">Methods & limitations <ArrowRight size={14} /></a></footer></main>
  </div>;
}
